name: Autograding Tests
on:
- push:
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: List directory
      run: ls -R  # Lists files and directories
    - name: Unit tests
      id: unit-tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 60  # Increased timeout to 60 seconds
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        UNIT-TESTS_RESULTS: "${{ steps.unit-tests.outputs.result }}"
      with:
        runners: unit-tests
